### 1. 게시글 목록 조회

GET {{baseUrl}}

### 2. 개별 게시글 조회

GET {{baseUrl}}/32

### 3. 게시글 등록
< {%
    request.variables.set("time", $timestamp)
%}

POST {{baseUrl}}
Content-Type: application/json

{
  "title": "HTTP 파일로 등록 요청 {{time}}",
  "content": "테스트",
  "writer": "똥지호"
}

### 4. 게시글 수정
PUT {{baseUrl}}/39
Content-Type: application/json

{
  "no": 39,
  "title": "수정 {{$timestamp}}",
  "content": "수정된 내용",
  "writer": "뚕지호호호"
}

### 5. 게시글 삭제
DELETE {{baseUrl}}/42
Content-Type: application/json